<?php
/**
 * CWR Export — Zero dependency Excel & PDF export
 * Uses native PHP ZipArchive for .xlsx and pure HTML for print-to-PDF
 * No Composer, no libraries required
 */
if ( ! defined( 'ABSPATH' ) ) exit;

require_once CWR_PLUGIN_DIR . 'includes/class-xlsx-writer.php';
require_once CWR_PLUGIN_DIR . 'includes/class-pdf-writer.php';

class CWR_Export {

    public static function export_excel( $week_start = null, $zone_id = 0, $church_id = 0 ) {
        $reports  = CWR_Database::get_all_reports( $week_start ?: null, $zone_id ?: null, $church_id ?: null );
        $filename = self::build_filename( 'christway-reports', $week_start, 'xlsx' );

        $headers = [
            'Church', 'Zone', 'Pastor', 'Week Start', 'Week End',
            'Sunday Att.', 'Midweek Att.', 'Total Att.',
            'Offering (N)', 'Tithe (N)', 'Other Income (N)',
            'Salvations', 'First Timers', 'Notes', 'Submitted At',
        ];

        $rows   = [];
        $t_sun  = 0; $t_mid = 0; $t_att = 0;
        $t_off  = 0; $t_tit = 0; $t_oth = 0;
        $t_sal  = 0; $t_fst = 0;

        foreach ( $reports as $r ) {
            $rows[] = [
                $r->church_name ?? '',
                $r->zone_name   ?? 'Unassigned',
                $r->pastor_name ?? '',
                $r->week_start,
                $r->week_end,
                (int)  $r->sunday_attendance,
                (int)  $r->midweek_attendance,
                (int)  $r->total_attendance,
                number_format( (float) $r->total_offering, 2, '.', '' ),
                number_format( (float) $r->total_tithe,    2, '.', '' ),
                number_format( (float) $r->other_income,   2, '.', '' ),
                (int)  $r->salvations,
                (int)  $r->first_timers,
                $r->notes ?? '',
                $r->submitted_at,
            ];
            $t_sun += (int)   $r->sunday_attendance;
            $t_mid += (int)   $r->midweek_attendance;
            $t_att += (int)   $r->total_attendance;
            $t_off += (float) $r->total_offering;
            $t_tit += (float) $r->total_tithe;
            $t_oth += (float) $r->other_income;
            $t_sal += (int)   $r->salvations;
            $t_fst += (int)   $r->first_timers;
        }

        $totals_row = [
            'TOTALS', '', '', '', '',
            $t_sun, $t_mid, $t_att,
            number_format( $t_off, 2, '.', '' ),
            number_format( $t_tit, 2, '.', '' ),
            number_format( $t_oth, 2, '.', '' ),
            $t_sal, $t_fst, '', '',
        ];

        $week_label = $week_start ?: 'All weeks';
        $summary_rows = [
            [ 'Report Period',      $week_label ],
            [ 'Reports Submitted',  count( $reports ) ],
            [ 'Total Sunday Att.',  $t_sun ],
            [ 'Total Midweek Att.', $t_mid ],
            [ 'Total Attendance',   $t_att ],
            [ 'Total Offering',     number_format( $t_off, 2 ) ],
            [ 'Total Tithe',        number_format( $t_tit, 2 ) ],
            [ 'Other Income',       number_format( $t_oth, 2 ) ],
            [ 'Total Salvations',   $t_sal ],
            [ 'Total First Timers', $t_fst ],
            [ 'Generated At',       date( 'd M Y H:i' ) . ' WAT' ],
            [ 'Generated By',       wp_get_current_user()->display_name ],
        ];

        $writer = new CWR_XlsxWriter();
        $writer->add_sheet( 'Summary',        [ 'Metric', 'Value' ], $summary_rows );
        $writer->add_sheet( 'Weekly Reports', $headers, array_merge( $rows, [ $totals_row ] ) );
        $writer->output( $filename );
    }

    public static function export_pdf( $week_start = null, $zone_id = 0, $church_id = 0 ) {
        $reports  = CWR_Database::get_all_reports( $week_start ?: null, $zone_id ?: null, $church_id ?: null );
        $filename = self::build_filename( 'christway-reports', $week_start, 'pdf' );

        $title    = 'Christ Way Church Treasure House - Weekly Reports';
        $subtitle = $week_start ? "Week of {$week_start}" : 'All weeks';

        $headers = [
            'Church', 'Zone', 'Week', 'Pastor',
            'Sunday', 'Midweek', 'Total Att.',
            'Offering', 'Tithe', 'Salvations', 'First Timers',
        ];

        $rows  = [];
        $t_sun = 0; $t_mid = 0; $t_att = 0;
        $t_off = 0; $t_tit = 0;
        $t_sal = 0; $t_fst = 0;

        foreach ( $reports as $r ) {
            $rows[] = [
                $r->church_name ?? '',
                $r->zone_name   ?? 'Unassigned',
                $r->week_start,
                $r->pastor_name ?? '',
                number_format( (int)   $r->sunday_attendance ),
                number_format( (int)   $r->midweek_attendance ),
                number_format( (int)   $r->total_attendance ),
                number_format( (float) $r->total_offering, 2 ),
                number_format( (float) $r->total_tithe,    2 ),
                number_format( (int)   $r->salvations ),
                number_format( (int)   $r->first_timers ),
            ];
            $t_sun += (int)   $r->sunday_attendance;
            $t_mid += (int)   $r->midweek_attendance;
            $t_att += (int)   $r->total_attendance;
            $t_off += (float) $r->total_offering;
            $t_tit += (float) $r->total_tithe;
            $t_sal += (int)   $r->salvations;
            $t_fst += (int)   $r->first_timers;
        }

        $totals_row = [
            'TOTALS', '', '', '',
            number_format( $t_sun ),
            number_format( $t_mid ),
            number_format( $t_att ),
            number_format( $t_off, 2 ),
            number_format( $t_tit, 2 ),
            number_format( $t_sal ),
            number_format( $t_fst ),
        ];

        $writer = new CWR_PdfWriter();
        $writer->render_report( $title, $subtitle, $headers, $rows, $totals_row, $filename );
    }

    private static function build_filename( $base, $week, $ext ) {
        $suffix = $week ? '-' . $week : '-' . date( 'Y-m-d' );
        return sanitize_file_name( $base . $suffix . '.' . $ext );
    }
}
